.TH GNOME-RECIPES "1" "" "GNOME" "User Commands"
.SH NAME
gnome-recipes \- A cooking recipe application for GNOME
.SH SYNOPSIS
gnome\-recipes [OPTIONS]
.SH DESCRIPTION
gnome-recipes is an easy-to-use application that will help you to discover
what to cook today, tomorrow, the rest of the week and for your special
occasions.
.SH OPTIONS
This program accepts the standard GNOME and GTK options.
.TP
\fB\-\-category\fR=\fI\,CATEGORY\/\fR
Show a category
.TP
\fB\-\-verbose\fR
Turn on verbose logging
.TP
\fB\-v\fR, \fB\-\-version\fR
Print the version and exit
.TP
\fB\-h\fR, \fB\-\-help\fR
Show help options
.SH "BUGS"
Please send bug reports to either the Debian bug tracker or the
upstream bug tracker at:
https://bugzilla\&.gnome\&.org/\:enter_bug\&.cgi?\:product=recipes.
.SH "SEE ALSO"
For further information visit the website at:
https://wiki\&.gnome\&.org/Apps/Recipes.
